import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DBC_DIR = REPO / "opendbc_repo" / "opendbc" / "dbc"
TESLA_RADAR_DBCS = (
  DBC_DIR / "tesla_radar_bosch_generated.dbc",
  DBC_DIR / "tesla_radar_continental_generated.dbc",
)


def test_minimal_scons_generates_tesla_radar_dbcs():
  for path in TESLA_RADAR_DBCS:
    path.unlink(missing_ok=True)

  result = subprocess.run(
    ["scons", "--minimal", "--no-cache", "opendbc_generated_dbcs"],
    cwd=REPO,
    capture_output=True,
    text=True,
    check=False,
  )
  assert result.returncode == 0, result.stdout + "\n" + result.stderr
  for path in TESLA_RADAR_DBCS:
    assert path.is_file(), f"{path.name} missing after scons --minimal"
    assert "AUTOGENERATED FILE" in path.read_text(encoding="utf-8")
