"""Bosch SensorDirty degrade mutation definitions (see tesla_preap_longitudinal_mutations.py).

NAPRadarIgnoreSensorDirty (default on) masks the radar's SensorDirty flag only while
live measured tracks exist, tags radarPreferReason, keeps the radar lead, warns through the
existing radarPreferFallback event (never a disable), and escalates to the old soft-disable only when the flag
persists SENSOR_DIRTY_PERSIST_S with no live track. Each entry breaks one rule of that
policy (or of the radarstat line) and must fail the pinned tests with an AssertionError.
"""
from tesla_preap_mutation_common import HistoricalMutation

T = "selfdrive/controls/tests/test_radar_sensor_dirty.py"
SD = "selfdrive/controls/lib/radar_sensor_dirty.py"
RADARD = "selfdrive/controls/radard.py"
EVENTS = "selfdrive/selfdrived/events.py"
SELFDRIVED = "selfdrive/selfdrived/selfdrived.py"
CARD = "selfdrive/car/card.py"
STAT = "selfdrive/controls/lib/radar_status_log.py"


def _m(name, path, original, replacement, *tests):
  return HistoricalMutation(
    name=name, source_path=path, original=original, replacement=replacement,
    test_nodes=tuple(f"{T}::{t}" for t in tests),
  )


MUTATIONS_F = (
  # --- policy constants and escalation ------------------------------------------------
  _m("dirty-persist-window-doubled", SD,
     b"SENSOR_DIRTY_PERSIST_S = 10.0\n", b"SENSOR_DIRTY_PERSIST_S = 20.0\n",
     "test_constants_are_pinned", "test_flag_without_live_tracks_escalates_after_persist_window"),
  _m("dirty-persist-window-shortened", SD,
     b"SENSOR_DIRTY_PERSIST_S = 10.0\n", b"SENSOR_DIRTY_PERSIST_S = 2.0\n",
     "test_constants_are_pinned", "test_live_tracks_keep_the_flag_masked_indefinitely",
     "test_flag_without_live_tracks_escalates_after_persist_window"),
  _m("dirty-live-recover-zero", SD,
     b"SENSOR_DIRTY_LIVE_RECOVER_S = 1.0\n", b"SENSOR_DIRTY_LIVE_RECOVER_S = 0.0\n",
     "test_constants_are_pinned", "test_brief_track_blip_does_not_restart_the_no_track_clock"),
  _m("dirty-escalation-never", SD,
     b"    self.escalated = self.no_track_s >= SENSOR_DIRTY_PERSIST_S\n",
     b"    self.escalated = False\n",
     "test_flag_without_live_tracks_escalates_after_persist_window",
     "test_radard_escalates_to_the_old_soft_disable_when_flag_persists_without_tracks"),
  _m("dirty-degraded-while-escalated", SD,
     b"    self.degraded = not self.escalated\n", b"    self.degraded = True\n",
     "test_flag_without_live_tracks_escalates_after_persist_window",
     "test_radard_escalates_to_the_old_soft_disable_when_flag_persists_without_tracks"),
  _m("dirty-live-tracks-inverted", SD,
     b"    if live_tracks:\n      self._live_s += dt\n", b"    if not live_tracks:\n      self._live_s += dt\n",
     "test_live_tracks_keep_the_flag_masked_indefinitely", "test_tracks_back_restart_the_clock_and_lift_the_escalation"),
  _m("dirty-no-track-clock-never-resets", SD,
     b"      if self._live_s >= SENSOR_DIRTY_LIVE_RECOVER_S:\n        self.no_track_s = 0.0\n",
     b"      if self._live_s >= SENSOR_DIRTY_LIVE_RECOVER_S:\n        pass\n",
     "test_live_tracks_keep_the_flag_masked_indefinitely", "test_tracks_back_restart_the_clock_and_lift_the_escalation"),
  _m("dirty-live-streak-not-broken-by-gap", SD,
     b"      self._live_s = 0.0\n      self.no_track_s += dt\n", b"      self.no_track_s += dt\n",
     "test_brief_track_blip_does_not_restart_the_no_track_clock"),
  _m("dirty-param-off-still-masks", SD,
     b"    if not ignore or not flag:\n", b"    if not flag:\n",
     "test_ignore_off_never_masks_and_never_degrades", "test_radard_param_off_keeps_the_old_soft_disable_flag"),
  _m("dirty-flag-clear-keeps-state", SD,
     b"    if not ignore or not flag:\n      self.reset()\n      return False\n",
     b"    if not ignore or not flag:\n      return False\n",
     "test_no_flag_never_masks_and_resets"),
  # --- param default --------------------------------------------------------------------
  _m("dirty-param-default-off", SD,
     b"  if params is None:\n    return True\n", b"  if params is None:\n    return False\n",
     "test_param_defaults_on_and_off_means_old_behavior"),
  _m("dirty-param-read-error-is-old-behavior", SD,
     b"    return bool(int(val)) if not isinstance(val, bool) else bool(val)\n  except Exception:\n    return True\n",
     b"    return bool(int(val)) if not isinstance(val, bool) else bool(val)\n  except Exception:\n    return False\n",
     "test_param_defaults_on_and_off_means_old_behavior"),
  _m("dirty-param-key-renamed", SD,
     b'SENSOR_DIRTY_PARAM = "NAPRadarIgnoreSensorDirty"\n', b'SENSOR_DIRTY_PARAM = "NAPRadarIgnoreSensorDirt"\n',
     "test_constants_are_pinned"),
  # --- reason token ---------------------------------------------------------------------
  _m("dirty-reason-token-drops-base", SD,
     b'  return f"{SENSOR_DIRTY_REASON}+{base}" if base else SENSOR_DIRTY_REASON\n',
     b"  return SENSOR_DIRTY_REASON\n",
     "test_reason_token_and_parse"),
  _m("dirty-reason-token-always-added", SD,
     b"  if not degraded:\n    return base\n", b"  if False:\n    return base\n",
     "test_reason_token_and_parse", "test_radard_clean_radar_has_no_sensor_dirty_trace"),
  _m("dirty-reason-parse-substring", SD,
     b'  return SENSOR_DIRTY_REASON in reason.split("+")\n', b"  return SENSOR_DIRTY_REASON in reason\n",
     "test_reason_token_and_parse"),
  _m("dirty-reason-parse-accepts-junk", SD,
     b"  if not isinstance(reason, str):\n    return False\n", b"  if not isinstance(reason, str):\n    return True\n",
     "test_reason_token_and_parse"),
  # --- radard ---------------------------------------------------------------------------
  _m("dirty-radard-mask-removed", RADARD,
     b"    if sensor_dirty_mask:\n      self.radar_state.radarErrors.radarUnavailableTemporary = False\n",
     b"    if False:\n      self.radar_state.radarErrors.radarUnavailableTemporary = False\n",
     "test_radard_masks_sensor_dirty_while_tracks_are_live_and_keeps_the_radar_lead"),
  _m("dirty-radard-warning-flag-dropped", RADARD,
     b"= bool(self.rain_gate.fallback_alert) or sensor_dirty_mask\n", b"= bool(self.rain_gate.fallback_alert)\n",
     "test_radard_masks_sensor_dirty_while_tracks_are_live_and_keeps_the_radar_lead"),
  _m("dirty-radard-masks-can-error-too", RADARD,
     b"      self.radar_state.radarErrors.radarUnavailableTemporary = False\n",
     b"      self.radar_state.radarErrors.radarUnavailableTemporary = False\n      self.radar_state.radarErrors.canError = False\n",
     "test_radard_never_masks_other_radar_errors"),
  _m("dirty-radard-reliability-sees-raw-flag", RADARD,
     b"tracks=self.tracks, errors=self.radar_state.radarErrors, v_ego=self.v_ego,",
     b"tracks=self.tracks, errors=rr.errors, v_ego=self.v_ego,",
     "test_radard_masks_sensor_dirty_while_tracks_are_live_and_keeps_the_radar_lead"),
  _m("dirty-radard-reason-untagged", RADARD,
     b"= reason_token(self.reliability.log_reason, sensor_dirty_mask)\n",
     b"= str(self.reliability.log_reason)\n",
     "test_radard_masks_sensor_dirty_while_tracks_are_live_and_keeps_the_radar_lead",
     "test_radard_escalates_to_the_old_soft_disable_when_flag_persists_without_tracks"),
  _m("dirty-radard-param-ignored", RADARD,
     b"      ignore=self.read_sensor_dirty_ignore())\n", b"      ignore=True)\n",
     "test_radard_param_off_keeps_the_old_soft_disable_flag"),
  _m("dirty-radard-default-param-off", RADARD,
     b"    return sensor_dirty_ignore_enabled(self.rain_gate._get_params())\n", b"    return False\n",
     "test_radard_default_param_is_read_from_params_and_defaults_on",
     "test_radard_masks_sensor_dirty_while_tracks_are_live_and_keeps_the_radar_lead"),
  _m("dirty-radard-unmeasured-counts-live", RADARD,
     b"      self._live_measured = any(rpt[3] for rpt in ar_pts.values())\n",
     b"      self._live_measured = bool(ar_pts)\n",
     "test_radard_unmeasured_tracks_do_not_count_as_live"),
  _m("dirty-radard-live-ignores-measured-flag-on-empty", RADARD,
     b"      sensor_dirty_flag, self._live_measured and not radar_timed_out, DT_MDL,\n",
     b"      sensor_dirty_flag, True, DT_MDL,\n",
     "test_radard_escalates_to_the_old_soft_disable_when_flag_persists_without_tracks",
     "test_radard_radar_going_silent_counts_as_no_live_tracks"),
  # --- alert / event wiring -------------------------------------------------------------
  _m("dirty-alert-warning-text-old", EVENTS,
     b'  if _radar_sensor_dirty_active(sm):\n    title, sub =', b'  if False:\n    title, sub =',
     "test_alert_text_switches_on_the_sensor_dirty_token"),
  _m("dirty-alert-permanent-text-old", EVENTS,
     b"  if _radar_sensor_dirty_active(sm):\n    return NormalPermanentAlert(",
     b"  if False:\n    return NormalPermanentAlert(",
     "test_alert_text_switches_on_the_sensor_dirty_token"),
  _m("dirty-alert-always-dirty", EVENTS,
     b"    return sensor_dirty_degraded(getattr(sm['radarState'], 'radarPreferReason', ''))\n",
     b"    return True\n",
     "test_alert_text_switches_on_the_sensor_dirty_token"),
  _m("dirty-alert-gains-no-entry", EVENTS,
     b"    ET.WARNING: radar_prefer_fallback_warning_alert,\n  },\n",
     b'    ET.WARNING: radar_prefer_fallback_warning_alert,\n    ET.NO_ENTRY: NoEntryAlert("Radar Sensor Dirty"),\n  },\n',
     "test_degraded_alert_is_a_warning_not_a_disable_or_no_entry"),
  _m("dirty-selfdrived-hard-event-changed", SELFDRIVED,
     b"    elif self.sm['radarState'].radarErrors.radarUnavailableTemporary:\n      self.events.add(EventName.radarTempUnavailable)\n",
     b"    elif self.sm['radarState'].radarErrors.radarUnavailableTemporary:\n      self.events.add(EventName.radarFault)\n",
     "test_selfdrived_wiring_is_unchanged_and_degrade_rides_the_fallback_event"),
  _m("dirty-param-key-default-off", "common/params_keys.h",
     b'{"NAPRadarIgnoreSensorDirty", {PERSISTENT, BOOL, "1"}}', b'{"NAPRadarIgnoreSensorDirty", {PERSISTENT, BOOL}}',
     "test_param_key_defaults_on"),
  # --- radarstat line -------------------------------------------------------------------
  _m("dirty-statlog-dirty-bit-moved", STAT, b"SGU_DIRTY_BIT = 44\n", b"SGU_DIRTY_BIT = 43\n",
     "test_status_log_bit_positions_match_the_ui_decoder", "test_status_log_decodes_the_oct4_sgu_frame"),
  _m("dirty-statlog-period-zero", STAT, b"LOG_PERIOD_S = 0.5\n", b"LOG_PERIOD_S = 0.0\n",
     "test_status_log_emits_two_hz_with_bits_and_summary"),
  _m("dirty-statlog-rate-state-not-kept", STAT, b"    self._last_log_t = now\n    rec: dict", b"    rec: dict",
     "test_status_log_emits_two_hz_with_bits_and_summary"),
  _m("dirty-statlog-stationary-threshold-wide", STAT, b"STATIONARY_VREL_MS = 1.5\n", b"STATIONARY_VREL_MS = 20.0\n",
     "test_status_log_track_summary_counts_the_barrier_signature"),
  _m("dirty-statlog-near-lateral-wide", STAT, b"NEAR_LATERAL_Y_M = 3.0\n", b"NEAR_LATERAL_Y_M = 8.0\n",
     "test_status_log_track_summary_counts_the_barrier_signature"),
  _m("dirty-statlog-near-range-wide", STAT, b"NEAR_LATERAL_D_M = 60.0\n", b"NEAR_LATERAL_D_M = 100.0\n",
     "test_status_log_track_summary_counts_the_barrier_signature"),
  _m("dirty-statlog-any-bus", STAT, b"  return (int(src) & 0x7F) == RADAR_BUS\n", b"  return True\n",
     "test_status_log_ignores_non_radar_bus_and_never_raises", "test_status_log_emits_two_hz_with_bits_and_summary"),
  _m("dirty-statlog-alert-names-swapped", STAT, b'"sensorBlinded", "plantModeActive"', b'"plantModeActive", "sensorBlinded"',
     "test_status_log_bit_positions_match_the_ui_decoder", "test_status_log_alert_names_cover_blinded_and_radome_heater"),
  _m("dirty-statlog-errors-escape", STAT, b"    except Exception:\n      return None\n", b"    except ZeroDivisionError:\n      return None\n",
     "test_status_log_ignores_non_radar_bus_and_never_raises"),
  _m("dirty-statlog-card-logs-every-car", CARD,
     b"self._radar_stat = RadarStatusLogger() if tesla_preap else None", b"self._radar_stat = RadarStatusLogger()",
     "test_card_wires_the_status_log_for_preap_only"),
  _m("dirty-statlog-card-line-dropped", CARD, b"        cloudlog.error(stat_line)\n", b"        pass\n",
     "test_card_wires_the_status_log_for_preap_only"),
)
